version: '3'

services:
  naming-server:
    build: 
        context: naming-server
        dockerfile: Dockerfile
        network: my-network
    ports:
        - 8761:8761
    container_name: "naming-server"
    
  config-server:
    build:
        context: config-server
        dockerfile: Dockerfile
        network: my-network
    container_name: "config-server"
    ports:
        - 8888:8888
    volumes:
        - ./git-localconfig-repo
    environment:
      eureka.client.enabled: 'true'
      eureka.host: naming-server
      eureka.instance.preferIpAddress: 'true'
    depends_on:
    - naming-server
      
  driver-service:
    build:
        context: driver-service
        dockerfile: Dockerfile
        network: my-network
    container_name: "driver-service"
    environment:
        eureka.client.enabled: 'true'
        eureka.host: naming-server
        eureka.instance.preferIpAddress: 'true'    
    depends_on:
    - naming-server
    - config-server
  ride-service:
    build:
        context: ride-service
        dockerfile: Dockerfile
        network: my-network
    container_name: "ride-service"
    environment:
        eureka.client.enabled: 'true'
        eureka.host: naming-server
        eureka.instance.preferIpAddress: 'true'  
    depends_on:
    - naming-server
    - config-server
    - driver-service
    - passenger-service
    
  passenger-service:
    build:
        context: passenger-service
        dockerfile: Dockerfile
        network: my-network
    environment:
        eureka.client.enabled: 'true'
        eureka.host: naming-server
        eureka.instance.preferIpAddress: 'true'
    container_name: "passenger-service"        
    depends_on:
    - naming-server
    - config-server
    
  api-gateway-service:
    build:
        context: api-gateway-service
        dockerfile: Dockerfile
        network: my-network
    container_name: "api-gateway-service"    
    environment:
        eureka.client.enabled: 'true'
        eureka.host: naming-server
        eureka.instance.preferIpAddress: 'true' 
    depends_on:
    - naming-server
    - config-server
    - driver-service
    - passenger-service
    - ride-service